### ISSUE TITLE
Can't open Android App

### ISSUE THREAD

**Issue by vrjmath** [WatShout/watshout-android#48]
I'm having this error and I'm not sure what it means. It could be that it can't connect to firebase.
![image](https://user-images.githubusercontent.com/29766196/42471547-edc39bbe-8372-11e8-9f74-894f5072d1c8.png)

**Comment by ethanzh** [comment]
This is super unhelpful, but I just downloaded a fresh copy of the repo and it launches fine on my Xiaomi phone. Maybe there was a Firebase outage while you were testing? Really not sure
