### ISSUE TITLE
Lag after selecting photo from gallery on first login

### ISSUE THREAD

**Issue by ethanzh** [WatShout/watshout-android#65]
After I select an image from the gallery the app hangs for around 20 seconds, shows a black screen, and then behaves as expected. Try to figure out what is causing this weird delay

**Comment by rsyed0** [comment]
Possibly caused by a permissions issue with `Manifest.permission.READ_EXTERNAL_STORAGE`, issue should be merged with rewriting the permissions system.

**Comment by rsyed0** [comment]
Image is probably taking a long time to upload because of its size. Some of these images are 1MB or greater, and so they need to be cropped/compressed before the upload.

**Comment by rsyed0** [comment]
Fix is tested/pushed
